targets:
  $default:
    builders:
      go_router_builder|router:
        enabled: true
        # generate_for:
        #   exclude:
        #     - test
        #     - example
        #   include:
        #     - lib/*.dart
        #     - test/integration/*
        #     - test/integration/**/*
        generate_for:
          - lib/*.dart
      go_router_builder|meta:
        enabled: false
        generate_for:
          - lib/*.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
